POST http://localhost:3001/user/start
Content-Type: application/json

{
  "chatId": "123455636827898",
  "firstName": "John",
  "lastName": "Doe",
  "username": "johndoe",
  "userId": "abc123973293"
}

###
POST http://localhost:3001/wallet/add-wallet
Content-Type: application/json

{
  
  "userId": "abc12397293",
  "walletAddresses":["FyNrn5ELHtimjCscVqRK11Q59VaH3knzahtcaPpcmSro"]
}


###
DELETE http://localhost:3001/wallet/delete-wallets 
Content-Type: application/json

{
  "userId": "abc12397293",
  "walletAddresses":["FyNrn5ELHtimjCscVqRK11Q59VaH3knzahtcaPpcmSro"]
}
